# Generated by Django 3.2.4 on 2021-06-05 08:00

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(max_length=200)),
                ('meta_title', models.CharField(blank=True, max_length=250, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma Separated Keyword for search engines', max_length=300, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/')),
                ('copyright_text', models.CharField(blank=True, max_length=120, null=True)),
                ('google_analytics_code', models.CharField(blank=True, help_text='Paste google analytics tracing code: ex. UA-69123876-4', max_length=50, null=True)),
                ('alexa_code', models.CharField(blank=True, max_length=50, null=True)),
                ('facebook', models.URLField(blank=True, help_text='Input your Facebook page url', null=True)),
                ('twitter', models.URLField(blank=True, help_text='Input your Twitter page url', null=True)),
                ('youtube', models.URLField(blank=True, help_text='Input your YouTube page url', null=True)),
                ('linkedin', models.URLField(blank=True, help_text='Input your LinkedIN page url', null=True)),
                ('instagram', models.URLField(blank=True, help_text='Input your Instagram page url', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=True, null=True, populate_from='username'),
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', tinymce.models.HTMLField()),
                ('content_image', models.ImageField(upload_to='content_images/')),
                ('image_caption', models.CharField(blank=True, max_length=200, null=True)),
                ('video_link', models.CharField(help_text='Input YouTube Video Embed Code', max_length=100)),
                ('is_home', models.BooleanField(help_text='Select this content for home page')),
                ('status', models.CharField(choices=[('D', 'Draft'), ('P', 'Published')], default='P', max_length=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=True, help_text='this-slug-must-be-english', populate_from=models.CharField(max_length=200), unique_with=['created__month', 'status'])),
                ('meta_title', models.CharField(blank=True, max_length=250, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma Separated Keyword for search engines', max_length=300, null=True)),
                ('main_category', models.ForeignKey(help_text='Select main category', on_delete=django.db.models.deletion.CASCADE, to='core.maincategory')),
            ],
        ),
    ]
