# Generated by Django 3.2.4 on 2021-12-30 20:06

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210605_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', autoslug.fields.AutoSlugField(editable=True, help_text='this-slug-must-be-english', populate_from=models.CharField(max_length=200), unique_with=['created__month', 'status'])),
                ('is_home', models.BooleanField(help_text='Select this content for home page')),
                ('description', tinymce.models.HTMLField()),
                ('content_image', models.ImageField(upload_to='content_images/')),
                ('image_caption', models.CharField(blank=True, max_length=200, null=True)),
                ('video_link', models.CharField(blank=True, help_text='Input YouTube Video Embed Code', max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=250, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma Separated Keyword for search engines', max_length=300, null=True)),
                ('status', models.CharField(choices=[('D', 'Draft'), ('P', 'Published')], default='P', max_length=1)),
                ('main_category', models.ForeignKey(help_text='Select main category', on_delete=django.db.models.deletion.CASCADE, to='core.maincategory')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
                'ordering': ['-created'],
            },
        ),
        migrations.DeleteModel(
            name='Content',
        ),
    ]
