# Generated by Django 3.2.4 on 2021-12-30 21:39

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20211231_0335'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, unique=True)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('sequence', models.CharField(blank=True, max_length=3, null=True)),
                ('status', models.CharField(choices=[('D', 'Draft'), ('P', 'Published')], default='P', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.AddField(
            model_name='news',
            name='news_room',
            field=models.ForeignKey(blank=True, help_text='Select news room', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.newsroom'),
        ),
    ]
