# Generated by Django 3.2.4 on 2021-12-31 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20211231_0339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='created',
        ),
        migrations.RemoveField(
            model_name='news',
            name='updated',
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
