# Generated by Django 3.2.4 on 2021-12-31 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_news_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='top_news',
            field=models.CharField(choices=[('S', 'Slider'), ('6', 'Top 6'), ('N', 'None')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
    ]
