# Generated by Django 3.2.4 on 2022-01-03 02:19

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_news_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.CharField(blank=True, max_length=200, unique=True)),
                ('description', tinymce.models.HTMLField()),
                ('content_image', models.ImageField(upload_to='content_images/')),
                ('image_caption', models.CharField(blank=True, max_length=200, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=250, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma Separated Keyword for search engines', max_length=300, null=True)),
                ('sequence', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('status', models.CharField(choices=[('D', 'Draft'), ('P', 'Published')], default='P', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='maincategory',
            name='sequence',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
